// packages/react/src/Divider.tsx
import { forwardRef } from "react";
import type { HTMLAttributes } from "react";
import { joinClasses } from "./styles.js";
import type { SensationStyles } from "./styles.js";
import { useTheme } from "./theme.js";

export interface DividerProps extends HTMLAttributes<HTMLDivElement> {
	readonly orientation?: "horizontal" | "vertical";
}

export const Divider = forwardRef<HTMLDivElement, DividerProps>(function Divider(
	{ className, orientation = "horizontal", style, ...divProps },
	ref,
) {
	const theme = useTheme();
	const dividerStyle: SensationStyles = {
		"--sensation-divider-color": theme.fgAtopBg,
		...style,
	};

	return (
		<div
			{...divProps}
			ref={ref}
			aria-orientation={orientation}
			className={joinClasses("sensation-divider", `sensation-divider--${orientation}`, className)}
			role="separator"
			style={dividerStyle}
		/>
	);
});

// packages/svelte/src/lib/Divider.svelte
<script module lang="ts">
	import type { HTMLAttributes } from "svelte/elements";

	export interface DividerProps extends HTMLAttributes<HTMLDivElement> {
		element?: HTMLDivElement | null;
		orientation?: "horizontal" | "vertical";
	}
</script>

<script lang="ts">
	import { mergeStyles } from "./styles.js";
	import { getThemeState } from "./theme-context.js";

	let {
		class: className,
		element = $bindable(null),
		orientation = "horizontal",
		style,
		...divProps
	}: DividerProps = $props();
	const themeState = getThemeState();
	const mergedStyle = $derived(
		mergeStyles(`--sensation-divider-color:${themeState.current.fgAtopBg}`, style),
	);
</script>

<div
	{...divProps}
	aria-orientation={orientation}
	bind:this={element}
	class={["sensation-divider", `sensation-divider--${orientation}`, className]}
	role="separator"
	style={mergedStyle}
></div>

<style>
	.sensation-divider {
		box-sizing: border-box;
		flex: none;
		border: 0;
		background: var(--sensation-divider-color);
		opacity: 0.2;
	}

	.sensation-divider--horizontal {
		inline-size: 100%;
		block-size: 1px;
	}

	.sensation-divider--vertical {
		inline-size: 1px;
		block-size: 100%;
	}
</style>
