// packages/react/src/Spacer.tsx
import { forwardRef } from "react";
import type { HTMLAttributes } from "react";
import { joinClasses } from "./styles.js";
import type { SensationStyles } from "./styles.js";

export interface SpacerProps extends HTMLAttributes<HTMLSpanElement> {
	readonly size: number | string;
}

function toCssLength(value: number | string): number | string {
	return typeof value === "number" ? `${value}px` : value;
}

export const Spacer = forwardRef<HTMLSpanElement, SpacerProps>(function Spacer(
	{ className, size, style, ...spanProps },
	ref,
) {
	const spacerStyle: SensationStyles = {
		"--sensation-spacer-size": toCssLength(size),
		...style,
	};

	return (
		<span
			{...spanProps}
			ref={ref}
			aria-hidden="true"
			className={joinClasses("sensation-spacer", className)}
			style={spacerStyle}
		/>
	);
});

// packages/svelte/src/lib/Spacer.svelte
<script module lang="ts">
	import type { HTMLAttributes } from "svelte/elements";

	export interface SpacerProps extends HTMLAttributes<HTMLSpanElement> {
		element?: HTMLSpanElement | null;
		size: number | string;
	}
</script>

<script lang="ts">
	import { mergeStyles } from "./styles.js";

	let {
		class: className,
		element = $bindable(null),
		size,
		style,
		...spanProps
	}: SpacerProps = $props();
	const cssSize = $derived(typeof size === "number" ? `${size}px` : size);
	const mergedStyle = $derived(mergeStyles(`--sensation-spacer-size:${cssSize}`, style));
</script>

<span
	{...spanProps}
	aria-hidden="true"
	bind:this={element}
	class={["sensation-spacer", className]}
	style={mergedStyle}
></span>

<style>
	.sensation-spacer {
		display: block;
		box-sizing: border-box;
		inline-size: var(--sensation-spacer-size);
		block-size: var(--sensation-spacer-size);
		flex: none;
	}
</style>
